---
- name: Install required dependencies for GraphicsMagick
  ansible.builtin.yum:
    name:
      - gcc
      - make
      - libjpeg-devel
      - libpng-devel
      - libtiff-devel
      - freetype-devel
      - libtool
      - ghostscript
      - xz  # Needed to extract .tar.xz
    state: present
  become: true

- name: Fetch SourceForge graphicsmagick directory page HTML
  ansible.builtin.uri:
    url: https://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/
    return_content: yes
  register: sf_html

- name: Extract latest GraphicsMagick version from HTML
  ansible.builtin.set_fact:
    gm_version: "{{ (sf_html.content | regex_findall('graphicsmagick/([0-9.]+)/')) | sort | last }}"

- name: Debug - show detected latest version
  ansible.builtin.debug:
    msg: "Latest GraphicsMagick version detected: {{ gm_version }}"

- name: Set download URL and filenames
  ansible.builtin.set_fact:
    gm_tarball: "GraphicsMagick-{{ gm_version }}.tar.xz"
    gm_url: "https://downloads.sourceforge.net/project/graphicsmagick/graphicsmagick/{{ gm_version }}/GraphicsMagick-{{ gm_version }}.tar.xz"

- name: Download GraphicsMagick source (.tar.xz)
  ansible.builtin.get_url:
    url: "{{ gm_url }}"
    dest: "/tmp/{{ gm_tarball }}"
    mode: '0644'

- name: Extract GraphicsMagick source
  ansible.builtin.unarchive:
    src: "/tmp/{{ gm_tarball }}"
    dest: /tmp/
    remote_src: yes

- name: Configure GraphicsMagick
  ansible.builtin.command: ./configure --enable-shared
  args:
    chdir: "/tmp/GraphicsMagick-{{ gm_version }}"
  become: true

- name: Compile GraphicsMagick
  ansible.builtin.shell: make -j$(nproc)
  args:
    chdir: "/tmp/GraphicsMagick-{{ gm_version }}"
  become: true

- name: Install GraphicsMagick
  ansible.builtin.command: make install
  args:
    chdir: "/tmp/GraphicsMagick-{{ gm_version }}"
  become: true

- name: Refresh shared library cache
  ansible.builtin.command: ldconfig
  become: true

- name: Clean up source and archive
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/GraphicsMagick-{{ gm_version }}"
    - "/tmp/{{ gm_tarball }}"