---
- name: Install dependencies for LibreOffice
  ansible.builtin.yum:
    name:
      - wget
      - tar
      - xz
      - libXinerama
      - libGLU
      - openssl
      - openssl-devel
      - nss
      - nss-tools
      - cairo
      - libxslt
      - cups-libs
    state: present
  become: true

- name: Fetch LibreOffice stable versions directory index
  ansible.builtin.uri:
    url: https://download.documentfoundation.org/libreoffice/stable/
    return_content: yes
  register: lo_versions_html

- name: Extract all LibreOffice version numbers
  ansible.builtin.set_fact:
    lo_versions: "{{ lo_versions_html.content | regex_findall('href=\"([0-9]+\\.[0-9]+\\.[0-9]+)/\"') | sort | unique }}"

- name: Select the latest LibreOffice version
  ansible.builtin.set_fact:
    lo_latest: "{{ lo_versions | last }}"

- name: Debug – show detected latest LibreOffice version
  ansible.builtin.debug:
    msg: "Latest LibreOffice version = {{ lo_latest }}"

- name: Set LibreOffice tarball filename
  ansible.builtin.set_fact:
    lo_tarball: "LibreOffice_{{ lo_latest }}_Linux_x86-64_rpm.tar.gz"

- name: Set LibreOffice download URL and filenames
  ansible.builtin.set_fact:
    lo_tarball: "LibreOffice_{{ lo_latest }}_Linux_x86-64_rpm.tar.gz"
    lo_url: "https://download.documentfoundation.org/libreoffice/stable/{{ lo_latest }}/rpm/x86_64/{{ lo_tarball }}"
    lo_extract_dir: "/tmp/LibreOffice_{{ lo_latest }}_Linux_x86-64_rpm"

- name: Download LibreOffice archive
  ansible.builtin.get_url:
    url: "{{ lo_url }}"
    dest: "/tmp/LibreOffice.tar.gz"
    mode: '0644'

- name: Extract LibreOffice archive
  ansible.builtin.unarchive:
    src: /tmp/LibreOffice.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Find extracted LibreOffice directory in /tmp
  ansible.builtin.find:
    paths: /tmp/
    patterns: 'LibreOffice_*_Linux_x86-64_rpm'
    file_type: directory
  register: extracted_dirs

- name: Set extracted LibreOffice directory fact
  ansible.builtin.set_fact:
    lo_extract_dir: "{{ extracted_dirs.files[0].path }}"

- name: Install LibreOffice RPMs in one transaction
  ansible.builtin.shell: >
    dnf install -y "{{ lo_extract_dir }}/RPMS/"*.rpm --nogpgcheck

- name: Set LibreOffice path in .bashrc for current user
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export PATH="{{ lo_extract_dir | regex_replace(".*/LibreOffice_(\\d+\\.\\d+).*", "/opt/libreoffice\\1/program") }}:$PATH"'
    insertafter: EOF
  become: true

- name: Reload shell environment for current user
  ansible.builtin.shell: source ~/.bashrc
  args:
    executable: /bin/bash

- name: Clean up LibreOffice archive and extracted files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ lo_extract_dir }}"
    - /tmp/LibreOffice.tar.gz