---
- name: Gather system facts
  ansible.builtin.setup:

- name: Disable known broken repo (mariadb-maxscale) if present
  ansible.builtin.command: dnf config-manager --set-disabled mariadb-maxscale
  become: true
  ignore_errors: true
  changed_when: false

- name: Install EPEL repository
  ansible.builtin.yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  become: true

- name: Install RPM Fusion free repository
  ansible.builtin.yum:
    name: "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  become: true

- name: Install RPM Fusion nonfree repository
  ansible.builtin.yum:
    name: "https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  become: true

- name: Enable PowerTools repo (CentOS/Rocky/Alma)
  ansible.builtin.command: dnf config-manager --set-enabled powertools
  become: true
  when: ansible_facts['distribution'] in ['AlmaLinux', 'Rocky', 'CentOS']

- name: Update all repository metadata
  ansible.builtin.command: dnf makecache
  become: true

# ✅ RHEL 10 and above: Install all multimedia packages
- name: Install multimedia packages (RHEL 10+)
  ansible.builtin.yum:
    name:
      - ladspa
      - rubberband
      - libdav1d
      - ffmpeg
      - ffmpeg-devel
    state: present
  become: true
  when: ansible_facts['distribution_major_version'] | int >= 10

# ✅ RHEL 9: Install only supported multimedia packages
- name: Install ffmpeg static binary (RHEL 9) (skip ladspa/rubberband)
  import_tasks: install_static_ffmpeg.yml
  when: ansible_facts['distribution_major_version'] | int == 9

- name: Clean yum caches
  ansible.builtin.command: dnf clean all
  become: true