---
- name: Gather system facts
  ansible.builtin.setup:

# Optional: Disable broken repo (like mariadb-maxscale) if it exists
- name: Disable known broken repo (mariadb-maxscale) if present
  ansible.builtin.command: dnf config-manager --set-disabled mariadb-maxscale
  become: true
  ignore_errors: true
  changed_when: false

# EPEL install (dynamic based on RHEL version)
- name: Install EPEL repository
  ansible.builtin.yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
    disablerepo:
     - mariadb-maxscale
  become: true

# RPM Fusion Free
- name: Install RPM Fusion free repository
  ansible.builtin.yum:
    name: "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  become: true

# RPM Fusion Nonfree
- name: Install RPM Fusion nonfree repository
  ansible.builtin.yum:
    name: "https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  become: true


# Optional: Enable PowerTools for Rocky/Alma/CentOS
- name: Enable PowerTools repo (CentOS/Rocky/Alma)
  ansible.builtin.command: dnf config-manager --set-enabled powertools
  become: true
  when: ansible_facts['distribution'] in ['AlmaLinux', 'Rocky', 'CentOS']

# Refresh metadata
- name: Update all repository metadata
  ansible.builtin.command: dnf makecache
  become: true

# Install your required packages (latest available)
- name: Install multimedia packages
  ansible.builtin.yum:
    name:
      - ladspa
      - rubberband
      - libdav1d
      - ffmpeg
      - ffmpeg-devel
    state: present
  become: true

# Clean yum/dnf cache
- name: Clean yum caches
  ansible.builtin.command: dnf clean all
  become: true