---
- name: Deploy Server Components
  hosts: local
  become: yes
  vars_files:
    - ../inventories/production/group_vars/all.yml

  tasks:
    - name: Include dependent_packages role
      include_role:
        name: dependent_packages

    - name: Include mariadb role
      include_role:
        name: mariadb

    - name: Include server role
      include_role:
        name: server

    - name: Run curl for dbcreator
      ansible.builtin.shell: |
        curl -s http://localhost:5000/dbcreator/create_db